///
/// File: cli.c
///       Command line interface for all fuzzing drivers
///
// Copyright (C) Microsoft Corporation
// SPDX-License-Identifier: MIT

#include <errno.h>
#include <getopt.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "common.h"
#include "driver.h"

typedef struct {
    bool iv_is_public;
    bool key_is_public;
    bool plaintext_is_public;
} policy_t;

#define ASSERT(cond, msg)                                                                          \
    if (!(cond)) {                                                                                 \
        fprintf(stderr, "Assertion failed: %s\n", msg);                                            \
        exit(EXIT_FAILURE);                                                                        \
    }

// =================================================================================================
// Command line interface
// =================================================================================================
static void print_usage(const char *program)
{
    fprintf(stderr, "Usage: %s -d data_file -p policy_file -o output_file\n", program);
    fprintf(stderr, "  -h         Show this help message\n");
    fprintf(stderr, "  -d file    File containing input data, which includes both private and "
                    "public inputs.\nThis file is normally generated by a fuzzer\n");
    fprintf(stderr, "  -p file    File describing the data classification policy\n");
    fprintf(stderr, "  -o file    Output file\n");
}

static int read_args(int argc, char *argv[], char **data_file, char **policy_file,
                     char **output_fname)
{
    int opt;
    while ((opt = getopt(argc, argv, "d:p:o:h")) != -1) {
        switch (opt) {
        case 'd':
            *data_file = optarg;
            break;
        case 'p':
            *policy_file = optarg;
            break;
        case 'o':
            *output_fname = optarg;
            break;
        case 'h':
            print_usage(argv[0]);
            return 1;
        default:
            print_usage(argv[0]);
            return 1;
        }
    }

    // Check required arguments
    if (!*data_file || !*policy_file || !*output_fname) {
        print_usage(argv[0]);
        return 1;
    }

    return 0; // success
}

// =================================================================================================
// Helper functions
// =================================================================================================

/// @brief Read entire file into buffer
static int read_file(const char *filename, uint8_t **buffer, size_t *size, size_t min_size,
                     size_t max_size)
{
    FILE *file = fopen(filename, "rb");
    if (!file) {
        fprintf(stderr, "Error: Cannot open file %s: %s\n", filename, strerror(errno));
        return -1;
    }

    // Get file size
    struct stat st;
    if (fstat(fileno(file), &st) != 0) {
        fprintf(stderr, "Error: Cannot stat file %s: %s\n", filename, strerror(errno));
        fclose(file);
        return -1;
    }

    if (st.st_size == 0) {
        fprintf(stderr, "Error: File %s is empty\n", filename);
        fclose(file);
        return -1;
    }

    if ((size_t)st.st_size < min_size) {
        fprintf(stderr, "Error: File %s is too small (%ld bytes, min %zu)\n", filename, st.st_size,
                min_size);
        fclose(file);
        return -1;
    }

    if ((size_t)st.st_size > max_size) {
        fprintf(stderr, "Error: File %s is too large (%ld bytes, max %zu)\n", filename, st.st_size,
                max_size);
        fclose(file);
        return -1;
    }

    *buffer = malloc(st.st_size);
    if (!*buffer) {
        fprintf(stderr, "Error: Cannot allocate %ld bytes for file %s\n", st.st_size, filename);
        fclose(file);
        return -1;
    }

    size_t bytes_read = fread(*buffer, 1, st.st_size, file);
    if (bytes_read != (size_t)st.st_size) {
        fprintf(stderr, "Error: Only read %zu of %ld bytes from %s\n", bytes_read, st.st_size,
                filename);
        free(*buffer);
        *buffer = NULL;
        fclose(file);
        return -1;
    }

    *size = st.st_size;
    fclose(file);
    return 0;
}

static int write_output(const char *filename, const uint8_t *data, size_t size)
{
    FILE *file = fopen(filename, "wb");
    if (!file) {
        fprintf(stderr, "Error: Cannot open output file %s: %s\n", filename, strerror(errno));
        return -1;
    }

    size_t bytes_written = fwrite(data, 1, size, file);
    if (bytes_written != size) {
        fprintf(stderr, "Error: Only wrote %zu of %zu bytes to output file %s\n", bytes_written,
                size, filename);
        fclose(file);
        return -1;
    }

    fclose(file);
    return 0;
}

// =================================================================================================
// Input parsing
// =================================================================================================

/// @brief Set the policy based on the policy file;
///        The policy file is a simple file with exactly three lines:
///        1. iv: pub or priv
///        2. key: pub or priv
///        3. plaintext: pub or priv
///        If the file is not in the expected format, it returns an error.
static int set_policy(const char *policy_fname, policy_t *policy)
{
    FILE *file = fopen(policy_fname, "r");
    if (!file) {
        fprintf(stderr, "Error: Cannot open policy file %s: %s\n", policy_fname, strerror(errno));
        return -1;
    }

    // A set of flags to check that all fields are set
    bool iv_set, key_set, plaintext_set = false;

    // Read each of the lines and set the policy accordingly
    char line[256];
    for (int i = 0; i < 3; i++) {
        if (!fgets(line, sizeof(line), file)) {
            fprintf(stderr, "Error: Failed to read line %d from policy file %s\n", i + 1,
                    policy_fname);
            fclose(file);
            return -1;
        }

        // Remove trailing newline character
        line[strcspn(line, "\n")] = '\0';

        if (strncmp(line, "iv: pub", 7) == 0) {
            policy->iv_is_public = true;
            iv_set = true;
        } else if (strncmp(line, "iv: priv", 8) == 0) {
            policy->iv_is_public = false;
            iv_set = true;
        } else if (strncmp(line, "key: pub", 8) == 0) {
            policy->key_is_public = true;
            key_set = true;
        } else if (strncmp(line, "key: priv", 9) == 0) {
            policy->key_is_public = false;
            key_set = true;
        } else if (strncmp(line, "plaintext: pub", 14) == 0) {
            policy->plaintext_is_public = true;
            plaintext_set = true;
        } else if (strncmp(line, "plaintext: priv", 15) == 0) {
            policy->plaintext_is_public = false;
            plaintext_set = true;
        } else {
            fprintf(stderr, "Error: Invalid line in policy file %s: %s\n", policy_fname, line);
            fclose(file);
            return -1;
        }
    }

    // Make sure that there are no extra lines in the policy file
    if (fgets(line, sizeof(line), file)) {
        fprintf(stderr, "Error: Extra line in policy file %s: %s\n", policy_fname, line);
        fclose(file);
        return -1;
    }

    // Make sure all fields are set
    if (!iv_set || !key_set || !plaintext_set) {
        fprintf(stderr, "Error: Not all fields are set in policy file %s\n", policy_fname);
        fclose(file);
        return -1;
    }

    fclose(file);
    return 0;
}

/// @brief Parse input files and fill the input_t structures
static int parse_inputs(const char *policy_fname, const char *data_fname, input_t *config,
                        input_t *iv, input_t *key, input_t *plaintext)
{
    // Read the policy
    policy_t policy = {0};
    if (set_policy(policy_fname, &policy))
        return -1;

    // Read the data file
    uint8_t *data = NULL;
    size_t data_size = 0;
    if (read_file(data_fname, &data, &data_size, MIN_TOTAL_SIZE, MAX_TOTAL_SIZE) != 0)
        return -1;

    // Get the fuzzing configuration from the input data
    ASSERT(data_size >= CONF_SIZE, "Input data is too small to contain configuration");
    config->data = data;
    config->size = CONF_SIZE;
    driver_config_t *config_parsed = (driver_config_t *)config->data;

    // Identify the boundary between public and private data based on the configuration
    const size_t total_size = data_size - CONF_SIZE;
    const size_t priv_size = (config_parsed->priv_ratio * total_size) / MAX_PRIV_RATIO;
    const size_t pub_size = total_size - priv_size;

    uint8_t *priv_data = data + CONF_SIZE;
    uint8_t *pub_data = data + CONF_SIZE + priv_size;
    size_t pub_cursor = 0, priv_cursor = 0;

    // Set input_t pointers according to the policy
    if (policy.iv_is_public) {
        ASSERT(pub_size >= pub_cursor + IV_SIZE, "Public data size is too small for IV");
        iv->data = pub_data + pub_cursor;
        iv->size = IV_SIZE;
        pub_cursor += IV_SIZE;
    } else {
        ASSERT(priv_size >= priv_cursor + IV_SIZE, "Private data size is too small for IV");
        iv->data = priv_data + priv_cursor;
        iv->size = IV_SIZE;
        priv_cursor += IV_SIZE;
    }

    if (policy.key_is_public) {
        ASSERT(pub_size >= pub_cursor + KEY_SIZE, "Public data size is too small for key");
        key->data = pub_data + pub_cursor;
        key->size = KEY_SIZE;
        pub_cursor += KEY_SIZE;
    } else {
        ASSERT(priv_size >= priv_cursor + KEY_SIZE, "Private data size is too small for key");
        key->data = priv_data + priv_cursor;
        key->size = KEY_SIZE;
        priv_cursor += KEY_SIZE;
    }

    if (policy.plaintext_is_public) {
        plaintext->data = pub_data + pub_cursor;
        plaintext->size = pub_size - pub_cursor; // Remaining public data is plaintext
    } else {
        plaintext->data = priv_data + priv_cursor;
        plaintext->size = priv_size - priv_cursor; // Remaining private data is plaintext
    }
    ASSERT(plaintext->size >= MIN_PLAINTEXT_SIZE, "Public data size is too small for plaintext");
    ASSERT(plaintext->size <= MAX_PLAINTEXT_SIZE, "Public data size is too large for plaintext");

    return 0;
}

// =================================================================================================
// Main
// =================================================================================================
int main(int argc, char *argv[])
{
    int result = 0;

    // The first heap allocation in the program must be allocation of the custom stack for SymCrypt.
    // This is required to ensure that the SymCrypt stack base address is independent of
    // the input data and of the environmental variables.
    void *new_stack = get_new_stack(STACK_SIZE);
    if (new_stack == NULL) {
        fprintf(stderr, "Failed to allocate new stack\n");
        return 1;
    }

    // Read and check CLI arguments
    char *data_fname, *policy_fname, *output_fname = NULL;
    if (read_args(argc, argv, &data_fname, &policy_fname, &output_fname) != 0) {
        return 1;
    }

    // Read input data
    input_t *config = malloc(sizeof(input_t));
    input_t *iv = malloc(sizeof(input_t));
    input_t *key = malloc(sizeof(input_t));
    input_t *plaintext = malloc(sizeof(input_t));
    if (!config || !iv || !key || !plaintext) {
        fprintf(stderr, "Failed to allocate memory for input structures\n");
        exit(EXIT_FAILURE);
    }
    if (parse_inputs(policy_fname, data_fname, config, iv, key, plaintext) != 0) {
        fprintf(stderr, "Failed to parse input files\n");
        exit(EXIT_FAILURE);
    }

    // Create a buffer for the output
    // The output size is guaranteed to be at most the size of the plaintext
    uint8_t *output_data = malloc(plaintext->size);
    if (!output_data) {
        perror("Failed to allocate memory for output data");
        exit(EXIT_FAILURE);
    }

    // Run the test
    if (runner_outer(config, iv, key, plaintext, output_data, new_stack)) {
        fprintf(stderr, "Runner failed\n");
        exit(EXIT_FAILURE);
    }

    // Write the produced data to the output file
    if (write_output(output_fname, output_data, plaintext->size) != 0) {
        fprintf(stderr, "Failed to write output file %s\n", output_fname);
        exit(EXIT_FAILURE);
    }

    return result;
}