working_dir: /home/stuxnot/repos/mpi/sca-fuzzer-example/consfuzz/
force_working_dir_overwrite: True
model_root: /home/stuxnot/.local/dynamorio/
afl_root: /nix/store/rsryn5rfik5ils07g7q9153q1khmfm94-aflplusplus-4.32c/bin
afl_seed_dir: ../sca-fuzzer-example/seeds/

